// AUTOGENERATED by packages/crypto-test-vectors/scripts/generate-auth-redesign-vectors.ts
// DO NOT EDIT BY HAND. Re-run the generator to refresh.

export interface BiometricKeyVector {
  id: string;
  userId: string;
  userEmail: string;
  seedHex: string;
  expectedSeedData: string;
  expectedSalt: string;
  /** Lowercase hex of the 32-byte PBKDF2-SHA256 output (10,000 iterations). */
  expectedKeyHex: string;
}

export const BIOMETRIC_KEY_VECTORS: ReadonlyArray<BiometricKeyVector> = [
  {
    "id": "01",
    "userId": "user-a",
    "userEmail": "a@example.test",
    "seedHex": "a6dbbd8ccf04da7ca841f067a0fb6ba283124e2f50fed2ee35269d4e6de2672a",
    "expectedSeedData": "ptu9jM8E2nyoQfBnoPtrooMSTi9Q/tLuNSadTm3iZyo=user-aa@example.testBrianni-Biometric-Key-v4",
    "expectedSalt": "Brianni-Biometric-Key-v4user-a",
    "expectedKeyHex": "5ee36e171dc498c12709af3316ed8de97355ca7b4c3384cc8ab2307fa7cbc663"
  },
  {
    "id": "02",
    "userId": "user-b",
    "userEmail": "b@example.test",
    "seedHex": "ca0dc1dda7c3cadab0d7d439c4604ed7f7b990a54c6e5074e0e9328379e4f2c0",
    "expectedSeedData": "yg3B3afDytqw19Q5xGBO1/e5kKVMblB04Okyg3nk8sA=user-bb@example.testBrianni-Biometric-Key-v4",
    "expectedSalt": "Brianni-Biometric-Key-v4user-b",
    "expectedKeyHex": "d604e73d04e64a1a83bec2e686c843aca639b576546bc15c1326ea11a542f4df"
  },
  {
    "id": "03",
    "userId": "cuid-cmf03qfg40000abcd1234efgh",
    "userEmail": "long.user@example.test",
    "seedHex": "4b6e7a7f4a9e5822e70bcc9796889b281c21326964bd761dbd916b0831f709a6",
    "expectedSeedData": "S256f0qeWCLnC8yXloibKBwhMmlkvXYdvZFrCDH3CaY=cuid-cmf03qfg40000abcd1234efghlong.user@example.testBrianni-Biometric-Key-v4",
    "expectedSalt": "Brianni-Biometric-Key-v4cuid-cmf03qfg40000abcd1234efgh",
    "expectedKeyHex": "c51b5af4fbf304786f0282de9c7c60514d03781fc3a1595e97eda9f1775d61a4"
  },
  {
    "id": "04",
    "userId": "u",
    "userEmail": "short@x.io",
    "seedHex": "f5245cd3015cb26658111c5f16712518190e5d88b3b395a65ad35263eafe6ed4",
    "expectedSeedData": "9SRc0wFcsmZYERxfFnElGBkOXYizs5WmWtNSY+r+btQ=ushort@x.ioBrianni-Biometric-Key-v4",
    "expectedSalt": "Brianni-Biometric-Key-v4u",
    "expectedKeyHex": "dde9a2729b8b8c90102e0e82eab970bc8147a153cb272315e9db42233bda2602"
  },
  {
    "id": "05",
    "userId": "user-with-plus",
    "userEmail": "plus+tag@example.test",
    "seedHex": "23cc61c7e7f0141e0a58ffbd833fabafe533520b58bbb13dfa90da5e71f26a0f",
    "expectedSeedData": "I8xhx+fwFB4KWP+9gz+rr+UzUgtYu7E9+pDaXnHyag8=user-with-plusplus+tag@example.testBrianni-Biometric-Key-v4",
    "expectedSalt": "Brianni-Biometric-Key-v4user-with-plus",
    "expectedKeyHex": "b45507a31dc2b1a2e06bc90d6b592a15233fbf8f8067c534af7ef396ecbc5e97"
  },
  {
    "id": "06",
    "userId": "user-unicode",
    "userEmail": "naïve.café@example.test",
    "seedHex": "2b1b8c6b41f5b3708b6d71bb54e2e10ff21a9671d9c7f6165032e1da84077e6a",
    "expectedSeedData": "KxuMa0H1s3CLbXG7VOLhD/IalnHZx/YWUDLh2oQHfmo=user-unicodenaïve.café@example.testBrianni-Biometric-Key-v4",
    "expectedSalt": "Brianni-Biometric-Key-v4user-unicode",
    "expectedKeyHex": "0cbd1a7546ee5399bd31d02d06d46c69b455fb0404e1d1cbecd9f0274ff8a9fd"
  },
  {
    "id": "07",
    "userId": "user-mixed",
    "userEmail": "Mixed.Case@Example.TEST",
    "seedHex": "76fbc9241188cb59c8a639ec9a7996f7ddc0b7049d7965c354af50e5dfe8f961",
    "expectedSeedData": "dvvJJBGIy1nIpjnsmnmW993AtwSdeWXDVK9Q5d/o+WE=user-mixedMixed.Case@Example.TESTBrianni-Biometric-Key-v4",
    "expectedSalt": "Brianni-Biometric-Key-v4user-mixed",
    "expectedKeyHex": "72bd301275cd7e596c5fe934e2522edce85d98cae2e49a09bc487003eb9b30eb"
  },
  {
    "id": "08",
    "userId": "user-empty-local",
    "userEmail": "a@b.c",
    "seedHex": "8e95f2626127dcc47e434069326b7430ee5ec9a5f20aacb26073e38874908e0a",
    "expectedSeedData": "jpXyYmEn3MR+Q0BpMmt0MO5eyaXyCqyyYHPjiHSQjgo=user-empty-locala@b.cBrianni-Biometric-Key-v4",
    "expectedSalt": "Brianni-Biometric-Key-v4user-empty-local",
    "expectedKeyHex": "ba53f1cf704a78933d8b6b60880b619a01a6ddd72682ad2f0b36614a6b30a7d6"
  },
  {
    "id": "09",
    "userId": "user-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "userEmail": "long.local.part.with.many.dots@subdomain.example.test",
    "seedHex": "812d8b2a818fea6fa532cec7d7c57d9f4756e04ca93a1519f059375e95f97c18",
    "expectedSeedData": "gS2LKoGP6m+lMs7H18V9n0dW4EypOhUZ8Fk3XpX5fBg=user-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxlong.local.part.with.many.dots@subdomain.example.testBrianni-Biometric-Key-v4",
    "expectedSalt": "Brianni-Biometric-Key-v4user-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "expectedKeyHex": "b0c496605b39936ceb1aacc11c63d72288aa232e802dc342763d4c466f8d9d6d"
  }
];

export const BIOMETRIC_KEY_VECTOR_INFO = "Brianni-Biometric-Key-v4";
