// AUTOGENERATED by packages/crypto-test-vectors/scripts/generate-auth-redesign-vectors.ts
// DO NOT EDIT BY HAND. Re-run the generator to refresh.

export interface SeedWrapperVector {
  id: string;
  userId: string;
  userEmail: string;
  seedHex: string;
  ivHex: string;
  expectedKeyData: string;
  expectedSalt: string;
  /** Lowercase hex of the 32-byte PBKDF2-SHA256 output (100,000 iterations). */
  expectedWrapKeyHex: string;
  /** Lowercase hex of AES-256-GCM ciphertext (excluding tag). */
  expectedCiphertextHex: string;
  /** Lowercase hex of the 16-byte AES-256-GCM auth tag. */
  expectedTagHex: string;
  /**
   * Canonical stored format per spec §Contract C:
   *   iv (12 bytes) || ciphertext (32 bytes) || tag (16 bytes) -> base64
   * This is what server persists in key_derivation_gate.encryptedSeed; the
   * test verifies pack/unpack of this exact string.
   */
  expectedEncryptedSeedB64: string;
}

export const SEED_WRAPPER_VECTORS: ReadonlyArray<SeedWrapperVector> = [
  {
    "id": "01",
    "userId": "user-a",
    "userEmail": "a@example.test",
    "seedHex": "a6dbbd8ccf04da7ca841f067a0fb6ba283124e2f50fed2ee35269d4e6de2672a",
    "ivHex": "35cc0fec854f9849de2d370b",
    "expectedKeyData": "user-a:a@example.test:brianni-seed-encryption-v1",
    "expectedSalt": "brianni-seed-salt-v1:user-a",
    "expectedWrapKeyHex": "af9cd04bc6cc0c4e03d99f29ac4591d2b42690fdce66278c450529fc62ab0f0e",
    "expectedCiphertextHex": "1fb923e4181fe0a5b34d0fe8c0ec5659488016077b6ca1a317fa88305cdc32f4",
    "expectedTagHex": "a6896845695e3a17833048600f5856cc",
    "expectedEncryptedSeedB64": "NcwP7IVPmEneLTcLH7kj5Bgf4KWzTQ/owOxWWUiAFgd7bKGjF/qIMFzcMvSmiWhFaV46F4MwSGAPWFbM"
  },
  {
    "id": "02",
    "userId": "user-b",
    "userEmail": "b@example.test",
    "seedHex": "ca0dc1dda7c3cadab0d7d439c4604ed7f7b990a54c6e5074e0e9328379e4f2c0",
    "ivHex": "65ec9d6ccfccc2e9e483f459",
    "expectedKeyData": "user-b:b@example.test:brianni-seed-encryption-v1",
    "expectedSalt": "brianni-seed-salt-v1:user-b",
    "expectedWrapKeyHex": "600cab734ea2ab9bd82f7f3cfb618ee356fe560936f47708216cf881a800d2d1",
    "expectedCiphertextHex": "94a2ef8b499ec552cb02dde91326ce2a32439c45c3bd8494f44e7e7292cb13c3",
    "expectedTagHex": "7f54fb05aab756adf6a0a894b8e6d36b",
    "expectedEncryptedSeedB64": "ZeydbM/Mwunkg/RZlKLvi0mexVLLAt3pEybOKjJDnEXDvYSU9E5+cpLLE8N/VPsFqrdWrfagqJS45tNr"
  },
  {
    "id": "03",
    "userId": "cuid-cmf03qfg40000abcd1234efgh",
    "userEmail": "long.user@example.test",
    "seedHex": "4b6e7a7f4a9e5822e70bcc9796889b281c21326964bd761dbd916b0831f709a6",
    "ivHex": "894fd0a056be6d2fb51c471a",
    "expectedKeyData": "cuid-cmf03qfg40000abcd1234efgh:long.user@example.test:brianni-seed-encryption-v1",
    "expectedSalt": "brianni-seed-salt-v1:cuid-cmf03qfg40000abcd1234efgh",
    "expectedWrapKeyHex": "4775402da41204c16e147a234ff6da5ab0543646b5cb8f58e20712e6fe2598f2",
    "expectedCiphertextHex": "95f20a46198e426d1eed2f33a6f89cb6fae5778aeb23e3c9d162b3ab15e0c91a",
    "expectedTagHex": "d9f3f488df402347ee65855f69666836",
    "expectedEncryptedSeedB64": "iU/QoFa+bS+1HEcalfIKRhmOQm0e7S8zpvictvrld4rrI+PJ0WKzqxXgyRrZ8/SI30AjR+5lhV9pZmg2"
  },
  {
    "id": "04",
    "userId": "u",
    "userEmail": "short@x.io",
    "seedHex": "f5245cd3015cb26658111c5f16712518190e5d88b3b395a65ad35263eafe6ed4",
    "ivHex": "ba6ec99e5aebad1002266646",
    "expectedKeyData": "u:short@x.io:brianni-seed-encryption-v1",
    "expectedSalt": "brianni-seed-salt-v1:u",
    "expectedWrapKeyHex": "bffa4b7aa9d4a8a7a21c2e486d52bf814996d22b78551a6ee6594a8bb5cec6ca",
    "expectedCiphertextHex": "84ab9f4b2a12d564613b940c56e11adaeae7f036cbcac9397997b0ae14c8bb19",
    "expectedTagHex": "9d47e6d669e017fd2478612ef02cf929",
    "expectedEncryptedSeedB64": "um7JnlrrrRACJmZGhKufSyoS1WRhO5QMVuEa2urn8DbLysk5eZewrhTIuxmdR+bWaeAX/SR4YS7wLPkp"
  },
  {
    "id": "05",
    "userId": "user-with-plus",
    "userEmail": "plus+tag@example.test",
    "seedHex": "23cc61c7e7f0141e0a58ffbd833fabafe533520b58bbb13dfa90da5e71f26a0f",
    "ivHex": "9fe1f09a5ad50bb84bbb5258",
    "expectedKeyData": "user-with-plus:plus+tag@example.test:brianni-seed-encryption-v1",
    "expectedSalt": "brianni-seed-salt-v1:user-with-plus",
    "expectedWrapKeyHex": "10588b99d98add187c295a7232aad1c81f18585361878eeedb616f74c772ed32",
    "expectedCiphertextHex": "47bb81488d66e1dba8c6876f4e53508bc955924e56eff45ced6f26f5f4e570d4",
    "expectedTagHex": "c8ec75bd5507324c8e3dd15e5399b14e",
    "expectedEncryptedSeedB64": "n+HwmlrVC7hLu1JYR7uBSI1m4duoxodvTlNQi8lVkk5W7/Rc7W8m9fTlcNTI7HW9VQcyTI490V5TmbFO"
  },
  {
    "id": "06",
    "userId": "user-unicode",
    "userEmail": "naïve.café@example.test",
    "seedHex": "2b1b8c6b41f5b3708b6d71bb54e2e10ff21a9671d9c7f6165032e1da84077e6a",
    "ivHex": "20f52a038bb7a3659de01137",
    "expectedKeyData": "user-unicode:naïve.café@example.test:brianni-seed-encryption-v1",
    "expectedSalt": "brianni-seed-salt-v1:user-unicode",
    "expectedWrapKeyHex": "ca219753ea52c1e12de928d69ff58c1f2dc5c009dabff73fdb5f70c93b54daba",
    "expectedCiphertextHex": "f3e97eba4bc7ede8b93590d74d23b2ceaf2d5bb964f37b537cfc7b07b377e242",
    "expectedTagHex": "f55fad97fee20d214fb074ecfe07bce4",
    "expectedEncryptedSeedB64": "IPUqA4u3o2Wd4BE38+l+ukvH7ei5NZDXTSOyzq8tW7lk83tTfPx7B7N34kL1X62X/uINIU+wdOz+B7zk"
  },
  {
    "id": "07",
    "userId": "user-mixed",
    "userEmail": "Mixed.Case@Example.TEST",
    "seedHex": "76fbc9241188cb59c8a639ec9a7996f7ddc0b7049d7965c354af50e5dfe8f961",
    "ivHex": "ae084e20fa328107baabd946",
    "expectedKeyData": "user-mixed:Mixed.Case@Example.TEST:brianni-seed-encryption-v1",
    "expectedSalt": "brianni-seed-salt-v1:user-mixed",
    "expectedWrapKeyHex": "fb7e6d23445861c4310f6568b85bddc72826676e46fea859e9cbb1f9e295666e",
    "expectedCiphertextHex": "cec5de14cc3b80b4d7336517179768b8598b778ad0b2fd1e66e35c2b24eb58ae",
    "expectedTagHex": "f726e777b7f67f568fcbda61f01a914b",
    "expectedEncryptedSeedB64": "rghOIPoygQe6q9lGzsXeFMw7gLTXM2UXF5douFmLd4rQsv0eZuNcKyTrWK73Jud3t/Z/Vo/L2mHwGpFL"
  },
  {
    "id": "08",
    "userId": "user-empty-local",
    "userEmail": "a@b.c",
    "seedHex": "8e95f2626127dcc47e434069326b7430ee5ec9a5f20aacb26073e38874908e0a",
    "ivHex": "2bb350935983c5c941f30bb0",
    "expectedKeyData": "user-empty-local:a@b.c:brianni-seed-encryption-v1",
    "expectedSalt": "brianni-seed-salt-v1:user-empty-local",
    "expectedWrapKeyHex": "3d3d41ecd63638251c65411cbf92192ac61b48c339264cade7f0ed7cd6f62e1d",
    "expectedCiphertextHex": "850cf33cb847ad13dd15d52006d5073d84e1c7c598c5e0cb3af1cfdf390d5928",
    "expectedTagHex": "b732e80b27fa5a283cbae5d87c82962c",
    "expectedEncryptedSeedB64": "K7NQk1mDxclB8wuwhQzzPLhHrRPdFdUgBtUHPYThx8WYxeDLOvHP3zkNWSi3MugLJ/paKDy65dh8gpYs"
  },
  {
    "id": "09",
    "userId": "user-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "userEmail": "long.local.part.with.many.dots@subdomain.example.test",
    "seedHex": "812d8b2a818fea6fa532cec7d7c57d9f4756e04ca93a1519f059375e95f97c18",
    "ivHex": "a4953a103bce76cdcc881d47",
    "expectedKeyData": "user-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:long.local.part.with.many.dots@subdomain.example.test:brianni-seed-encryption-v1",
    "expectedSalt": "brianni-seed-salt-v1:user-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "expectedWrapKeyHex": "293f82dc63972d9e01cb5a180bf9ff058470987faf4e008df64f25732c0d2489",
    "expectedCiphertextHex": "b1e1318390af5c6057400c742e6061bfab1620bd1596a7592fa68435145b68d9",
    "expectedTagHex": "f5e89e8a879c6081b625a8a28088d9e1",
    "expectedEncryptedSeedB64": "pJU6EDvOds3MiB1HseExg5CvXGBXQAx0LmBhv6sWIL0VlqdZL6aENRRbaNn16J6Kh5xggbYlqKKAiNnh"
  }
];
