/**
 * Stylometric engine cross-platform parity vectors.
 *
 * Generated by scripts/_gen-vectors.test.ts. Regenerate when rules or
 * dictionaries change.
 *
 * These vectors pin the exact StyleSuggestion output (including the
 * 16-char sha256 id) for a representative set of inputs. Mobile (Hermes)
 * and web (V8) must both reproduce these IDs byte-for-byte; otherwise
 * downstream logic that de-duplicates accepted suggestions by ID will
 * break across platforms.
 */

import type { StyleSuggestion } from '@calypso/masking-core';

export interface StylometricVector {
  input: string;
  expected: StyleSuggestion[];
}

export const STYLOMETRIC_VECTORS: readonly StylometricVector[] = [
  {
    input: 'Wait!!! Stop',
    expected: [
      {
        id: '1e4b00345dc3bcaa',
        category: 'punctuation',
        original: '!!!',
        replacement: '!',
        startIndex: 4,
        endIndex: 7,
        confidence: 1,
      },
    ],
  },
  {
    input: 'Hmm... maybe',
    expected: [
      {
        id: '9a52079b1e806d9c',
        category: 'punctuation',
        original: '...',
        replacement: '.',
        startIndex: 3,
        endIndex: 6,
        confidence: 1,
      },
    ],
  },
  {
    input: "I can't sleep",
    expected: [
      {
        id: '8513e4a57d529bee',
        category: 'contraction',
        original: "can't",
        replacement: 'cannot',
        startIndex: 2,
        endIndex: 7,
        confidence: 1,
      },
    ],
  },
  {
    input: "We've gotta go",
    expected: [
      {
        id: 'b506fae07a44bb9e',
        category: 'contraction',
        original: "We've",
        replacement: 'We have',
        startIndex: 0,
        endIndex: 5,
        confidence: 1,
      },
      {
        id: '17ba713150a75855',
        category: 'contraction',
        original: 'gotta',
        replacement: 'got to',
        startIndex: 6,
        endIndex: 11,
        confidence: 1,
      },
    ],
  },
  {
    input: 'I am SCREAMING loudly',
    expected: [
      {
        id: '6e552720b3f3d761',
        category: 'case',
        original: 'SCREAMING',
        replacement: 'screaming',
        startIndex: 5,
        endIndex: 14,
        confidence: 1,
      },
    ],
  },
  {
    input: 'Basically, I agree',
    expected: [
      {
        id: '966f07ed2f0a84aa',
        category: 'filler',
        original: 'Basically, ',
        replacement: '',
        startIndex: 0,
        endIndex: 11,
        confidence: 0.8,
      },
    ],
  },
  {
    input: 'It is a game-changer',
    expected: [
      {
        id: 'd9d541dad8666185',
        category: 'idiom',
        original: 'game-changer',
        replacement: 'significant improvement',
        startIndex: 8,
        endIndex: 20,
        confidence: 1,
      },
    ],
  },
  {
    input:
      'alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha and beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta beta.',
    expected: [
      {
        id: 'a0366342a415da81',
        category: 'sentence_length',
        original: ' and beta',
        replacement: '. Beta',
        startIndex: 179,
        endIndex: 188,
        confidence: 1,
      },
    ],
  },
  {
    input: 'before ```!!!``` after',
    expected: [],
  },
  {
    input: 'visit https://example.com/!!! now',
    expected: [],
  },
  {
    input: "Honestly, it's a no-brainer!!!",
    expected: [
      {
        id: '8c690c96b7c475bb',
        category: 'filler',
        original: 'Honestly, ',
        replacement: '',
        startIndex: 0,
        endIndex: 10,
        confidence: 0.8,
      },
      {
        id: 'e7a91b2b088253eb',
        category: 'contraction',
        original: "it's",
        replacement: 'it is',
        startIndex: 10,
        endIndex: 14,
        confidence: 1,
      },
      {
        id: '52ad28d08fb50082',
        category: 'idiom',
        original: 'no-brainer',
        replacement: 'obvious choice',
        startIndex: 17,
        endIndex: 27,
        confidence: 1,
      },
      {
        id: 'e5cf886f77cff2f9',
        category: 'punctuation',
        original: '!!!',
        replacement: '!',
        startIndex: 27,
        endIndex: 30,
        confidence: 1,
      },
    ],
  },
  {
    input: "I don't know what to say???",
    expected: [
      {
        id: '0cc9df3105c3ee06',
        category: 'contraction',
        original: "don't",
        replacement: 'do not',
        startIndex: 2,
        endIndex: 7,
        confidence: 1,
      },
      {
        id: 'e442b27a36230a55',
        category: 'punctuation',
        original: '???',
        replacement: '?',
        startIndex: 24,
        endIndex: 27,
        confidence: 1,
      },
    ],
  },
  {
    input: 'Really, we need to touch base.',
    expected: [
      {
        id: '68faae5676c18eb5',
        category: 'filler',
        original: 'Really, ',
        replacement: '',
        startIndex: 0,
        endIndex: 8,
        confidence: 0.8,
      },
      {
        id: '24310f5e8622eded',
        category: 'idiom',
        original: 'touch base',
        replacement: 'check in',
        startIndex: 19,
        endIndex: 29,
        confidence: 1,
      },
    ],
  },
  {
    input: 'Basically, the API is LOVING it.',
    expected: [
      {
        id: '966f07ed2f0a84aa',
        category: 'filler',
        original: 'Basically, ',
        replacement: '',
        startIndex: 0,
        endIndex: 11,
        confidence: 0.8,
      },
      {
        id: '7ce7f82e2c62ab26',
        category: 'case',
        original: 'LOVING',
        replacement: 'loving',
        startIndex: 22,
        endIndex: 28,
        confidence: 1,
      },
    ],
  },
  {
    input: 'At the end of the day, we won.',
    expected: [
      {
        id: '95db9550f6dae7bb',
        category: 'idiom',
        original: 'At the end of the day',
        replacement: 'ultimately',
        startIndex: 0,
        endIndex: 21,
        confidence: 1,
      },
    ],
  },
  {
    input: "Can't wait to circle back on this.",
    expected: [
      {
        id: 'f54d3e7678217358',
        category: 'contraction',
        original: "Can't",
        replacement: 'Cannot',
        startIndex: 0,
        endIndex: 5,
        confidence: 1,
      },
      {
        id: '570cf2cb5f799cd2',
        category: 'idiom',
        original: 'circle back',
        replacement: 'return to',
        startIndex: 14,
        endIndex: 25,
        confidence: 1,
      },
    ],
  },
  {
    input: 'We should move the needle on synergy.',
    expected: [
      {
        id: '3d3f78afa1fd3395',
        category: 'idiom',
        original: 'move the needle',
        replacement: 'make progress',
        startIndex: 10,
        endIndex: 25,
        confidence: 1,
      },
      {
        id: '38b78f2a1b9e1769',
        category: 'idiom',
        original: 'synergy',
        replacement: 'collaboration',
        startIndex: 29,
        endIndex: 36,
        confidence: 1,
      },
    ],
  },
  {
    input: "Going forward, I'll be in the loop.",
    expected: [
      {
        id: 'b478901df667dff2',
        category: 'idiom',
        original: 'Going forward',
        replacement: 'from now on',
        startIndex: 0,
        endIndex: 13,
        confidence: 1,
      },
      {
        id: '748550b1ddddfefc',
        category: 'contraction',
        original: "I'll",
        replacement: 'I will',
        startIndex: 15,
        endIndex: 19,
        confidence: 1,
      },
      {
        id: '61045eaf7a29328a',
        category: 'idiom',
        original: 'in the loop',
        replacement: 'informed',
        startIndex: 23,
        endIndex: 34,
        confidence: 1,
      },
    ],
  },
  {
    input: 'Em dash — here and there.',
    expected: [
      {
        id: 'b49017ffd2c1901a',
        category: 'punctuation',
        original: '—',
        replacement: '--',
        startIndex: 8,
        endIndex: 9,
        confidence: 1,
      },
    ],
  },
  {
    input: "Maybe, just maybe, it's gonna work???",
    expected: [
      {
        id: 'f4439f82772adf15',
        category: 'filler',
        original: 'Maybe, ',
        replacement: '',
        startIndex: 0,
        endIndex: 7,
        confidence: 0.8,
      },
      {
        id: '02fcda478e64637a',
        category: 'contraction',
        original: "it's",
        replacement: 'it is',
        startIndex: 19,
        endIndex: 23,
        confidence: 1,
      },
      {
        id: 'fb9267eb5abcac87',
        category: 'contraction',
        original: 'gonna',
        replacement: 'going to',
        startIndex: 24,
        endIndex: 29,
        confidence: 1,
      },
      {
        id: '028bb1a43ebe3ccc',
        category: 'punctuation',
        original: '???',
        replacement: '?',
        startIndex: 34,
        endIndex: 37,
        confidence: 1,
      },
    ],
  },
];
