// AUTOGENERATED by packages/crypto-test-vectors/scripts/generate-auth-redesign-vectors.ts
// DO NOT EDIT BY HAND. Re-run the generator to refresh.

export interface VerificationBlobVector {
  id: string;
  /** Lowercase hex of the 32-byte chat-root key. */
  chatRootHex: string;
  /** Lowercase hex of the 12-byte AES-GCM IV. */
  ivHex: string;
  /**
   * Expected serialised envelope JSON with sorted keys:
   *   {"ciphertext":"<b64>","iv":"<b64>","tag":"<b64>","v":1}
   * Plaintext is the literal "BRIANNI_AI_VERIFIED_v1".
   */
  expectedEnvelopeJson: string;
}

export const VERIFICATION_BLOB_VECTORS: ReadonlyArray<VerificationBlobVector> = [
  {
    "id": "01",
    "chatRootHex": "818de27d6e640c3220a7e894f9a6a8e5045a692d98b88c6ace9fd1df3784de1f",
    "ivHex": "b61ef63abffba3381a182607",
    "expectedEnvelopeJson": "{\"ciphertext\":\"pJLQ9yEQ4pl3pBp6840UkKZUeKo0Wg==\",\"iv\":\"th72Or/7ozgaGCYH\",\"tag\":\"FxZ7SdHI2LBLuOb8q/K9og==\",\"v\":1}"
  },
  {
    "id": "02",
    "chatRootHex": "5a9255f2430c2473d82a911dfdd9eec3db614804e5ab48604e77f9d8aefd2688",
    "ivHex": "53e1622a73e70e933487461b",
    "expectedEnvelopeJson": "{\"ciphertext\":\"v9tR9ta+BiJPLKJ8BHMpsogVGl/esw==\",\"iv\":\"U+FiKnPnDpM0h0Yb\",\"tag\":\"5LMht9JHrUQGOudMpbW70w==\",\"v\":1}"
  },
  {
    "id": "03",
    "chatRootHex": "cb145b0f0637a9111df4d3e905907b836a07af5cebaf4f08f3b2c4dca68dd83f",
    "ivHex": "7e9f5787e2686c00dfd55eac",
    "expectedEnvelopeJson": "{\"ciphertext\":\"EkzdQHw12HmDZjBMFhBK1RYxefyz2Q==\",\"iv\":\"fp9Xh+JobADf1V6s\",\"tag\":\"OQHP3Lua0FLRkwkNewKShA==\",\"v\":1}"
  },
  {
    "id": "04",
    "chatRootHex": "9a4ed1c00c58095377dea741d894b4e9af458383101e39f287eab8eddbaa8f82",
    "ivHex": "de168233c0430c9e5272559b",
    "expectedEnvelopeJson": "{\"ciphertext\":\"XSwgnL7hd9SspTeDMXQ2OvL169JJ1A==\",\"iv\":\"3haCM8BDDJ5SclWb\",\"tag\":\"vHYZNSoKsHeDi2imzPGXLg==\",\"v\":1}"
  },
  {
    "id": "05",
    "chatRootHex": "b2f8c9d97e94af0f478626be4dc159bb940e83133102615ad7b06c52b987a8fb",
    "ivHex": "2e5e33084085b7310530b24a",
    "expectedEnvelopeJson": "{\"ciphertext\":\"1cB4g8iVd9ODrs3TUmfhZJ7Uq98zFg==\",\"iv\":\"Ll4zCECFtzEFMLJK\",\"tag\":\"gam3yLQS8xWo7sQLl8kfBw==\",\"v\":1}"
  },
  {
    "id": "06",
    "chatRootHex": "79039439ece9ffa9dcc9e0a1e7c847576f924c8758de8d9ac8bdbd96b070474e",
    "ivHex": "f1a83c19dcc330c0b295dff6",
    "expectedEnvelopeJson": "{\"ciphertext\":\"ILtSWHbFqSTMYKOxHS6RyVePtsWP+Q==\",\"iv\":\"8ag8GdzDMMCyld/2\",\"tag\":\"nAk65uNKW/q9wwGWlfw0Qw==\",\"v\":1}"
  },
  {
    "id": "07",
    "chatRootHex": "4d5c0f38e4c07236b2a0dbd5edc5737bbc09f309c496d100e912a7855cdf92e8",
    "ivHex": "4765786ef912ec5d05f3e15b",
    "expectedEnvelopeJson": "{\"ciphertext\":\"nTO2NQYTJ/X1IdKZ6vpflFIvqA8Lng==\",\"iv\":\"R2V4bvkS7F0F8+Fb\",\"tag\":\"LiKYOcKSS9vbyqVNu2FIbQ==\",\"v\":1}"
  },
  {
    "id": "08",
    "chatRootHex": "f10de6345abc7e6eb4b56c112d06e2e611386d5eaa4109f18806fe84c50722fc",
    "ivHex": "973fbc1973a456c7b53a6ed5",
    "expectedEnvelopeJson": "{\"ciphertext\":\"kQJi8d48WkxD1oByhk+ARyh82MEtTA==\",\"iv\":\"lz+8GXOkVse1Om7V\",\"tag\":\"yj/gFZS3hC5EDDQN54ALng==\",\"v\":1}"
  },
  {
    "id": "09",
    "chatRootHex": "d35e8c13732bc4a73dc093ad7cefbea364e8b26d252726268c868950ca0c1565",
    "ivHex": "a14bb48daab5b9828f7e593d",
    "expectedEnvelopeJson": "{\"ciphertext\":\"VqDoBukUjScnvLBVsE2+kzMdgHlbIQ==\",\"iv\":\"oUu0jaq1uYKPflk9\",\"tag\":\"BP9XoEXydybOc1dMhvcLXg==\",\"v\":1}"
  }
];
